-- Stargate SG-1 SGC Construction Robot
-- Minecraft 1.7.10 / OpenComputers
-- Standalone builder; does NOT require MATRIX-OS.
--
-- This bootstrap deliberately refuses to build until a validated plan is installed.
-- The final schematic/plan is generated from the validated SGC reconstruction.

local component = require("component")
local computer = require("computer")
local event = require("event")
local filesystem = require("filesystem")

local robot = component.robot
local inv = component.inventory_controller
local modem = component.isAvailable("modem") and component.modem or nil

local PLAN = "/home/sgc/SGC-SG1-Cheyenne-Mountain.plan"
local PROGRESS = "/home/sgc/build-progress.cfg"

local function say(s)
  io.write("[SGC] " .. tostring(s) .. "\n")
end

local function fail(s)
  say("ERROR: " .. tostring(s))
  return false
end

local function exists(path)
  return filesystem.exists(path)
end

local function loadPlan(path)
  if not exists(path) then
    return nil, "No validated build plan installed: " .. path
  end
  local ok, data = pcall(dofile, path)
  if not ok or type(data) ~= "table" then
    return nil, "Invalid build plan"
  end
  if type(data.width) ~= "number" or type(data.height) ~= "number" or type(data.length) ~= "number" then
    return nil, "Plan dimensions missing"
  end
  if type(data.blocks) ~= "table" then
    return nil, "Plan block table missing"
  end
  return data
end

local function loadProgress()
  if not exists(PROGRESS) then return {index = 1} end
  local ok, p = pcall(dofile, PROGRESS)
  if ok and type(p) == "table" and type(p.index) == "number" then return p end
  return {index = 1}
end

local function saveProgress(index)
  local f = io.open(PROGRESS, "w")
  if not f then return false end
  f:write("return { index = ", tostring(index), " }\n")
  f:close()
  return true
end

local function placeSlot(slot)
  if not inv or not inv.suckFromSlot then return fail("Inventory controller required") end
  robot.select(slot)
  return robot.place()
end

local function moveForward()
  for _ = 1, 3 do
    if robot.forward() then return true end
    if robot.detect() then
      robot.swing()
    else
      computer.beep(900, 0.05)
    end
  end
  return false
end

local function moveToLayer(x, y, z)
  -- Position tracking/path planning is completed from the final validated plan.
  -- This function is intentionally conservative rather than guessing coordinates.
  return true
end

local function build(plan)
  local progress = loadProgress()
  local total = #plan.blocks
  say("Plan: " .. plan.width .. " x " .. plan.height .. " x " .. plan.length)
  say("Blocks: " .. total)
  say("Resume index: " .. progress.index)

  for i = progress.index, total do
    local b = plan.blocks[i]
    if type(b) ~= "table" then return fail("Invalid block entry " .. i) end

    -- Coordinates and inventory slot are generated by the schematic compiler.
    -- Never guess block IDs or protected-shaft coordinates here.
    if b.protected then
      -- Empty/protected volume: deliberately skip placement.
    elseif b.slot then
      if not moveToLayer(b.x, b.y, b.z) then return fail("Cannot reach " .. i) end
      if not placeSlot(b.slot) then
        saveProgress(i)
        return fail("Placement failed at block " .. i)
      end
    end

    if i % 25 == 0 then
      saveProgress(i + 1)
      say("Progress " .. math.floor(i * 100 / math.max(total, 1)) .. "%")
    end
  end

  saveProgress(total + 1)
  say("BUILD COMPLETE")
  return true
end

say("SGC Construction Robot - OpenComputers 1.7.10")
say("Standalone mode: MATRIX-OS is not used.")

if not robot then return fail("Robot component missing") end

local plan, err = loadPlan(PLAN)
if not plan then
  say(err)
  say("Install the validated SGC plan before starting the builder.")
  return
end

build(plan)
